version: "3.3"
services:
  binotify-rest-service-app:
    build: .
    image: binotify-rest-service-app:latest
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 8080:80

  binotify-rest-service-db:
    image: mysql:latest
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
