version: "3.3"
services:
  binotify-rest-service-app:
    build: .
    image: binotify-rest-service-app:latest
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - ${BINOTIFY_REST_SERVICE_APP_PORT:-8080}:${BINOTIFY_REST_SERVICE_APP_PORT:-8080}
    depends_on:
      binotify-rest-service-db:
        condition: service_healthy

  binotify-rest-service-db:
    image: mysql:latest
    restart: always
    ports:
      - ${BINOTIFY_REST_SERVICE_DB_PORT:-13306}:3306
    environment:
      MYSQL_DATABASE: "${BINOTIFY_REST_SERVICE_DB_NAME:-database}"
      MYSQL_USER: "${BINOTIFY_REST_SERVICE_DB_USER:-user}"
      MYSQL_PASSWORD: "${BINOTIFY_REST_SERVICE_DB_PASSWORD:-password}"
      MYSQL_ROOT_PASSWORD: "${BINOTIFY_REST_SERVICE_DB_ROOT_PASSWORD:-password}"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

    binotify-rest-service-cache:
      image: redis:7.0-alpine
      restart: always
      ports:
        - "6379:6379"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
