version: "3.3"
services:
  binotify-rest-service-app:
    build: .
    image: binotify-rest-service-app:latest
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - ${BINOTIFY_REST_SERVICE_APP_PORT:-8080}:${BINOTIFY_REST_SERVICE_APP_PORT:-8080}

  binotify-rest-service-db:
    image: mysql:latest
    restart: always
    ports:
      - ${BINOTIFY_REST_SERVICE_DB_PORT:-13306}:3306
    environment:
      MYSQL_DATABASE: "${BINOTIFY_REST_SERVICE_DB_NAME:-database}"
      MYSQL_USER: "${BINOTIFY_REST_SERVICE_DB_USER:-user}"
      MYSQL_PASSWORD: "{BINOTIFY_REST_SERVICE_DB_PASSWORD:-password}"
      MYSQL_ROOT_PASSWORD: "{BINOTIFY_REST_SERVICE_DB_ROOT_PASSWORD:-password}"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
